---
- name: Create /etc/hosts entries from inventory (non-local cluster)
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_ssh_host }} {{ item }}" state=present
  with_items: "{{ groups.all }}"

- name: Add additinal host entries
  lineinfile: dest=/etc/hosts regexp='.*{{ item.name }}$' line="{{ item.ip }} {{ item.name }}" state=present
  with_items: additional_hosts_entries
  when: additional_hosts_entries is defined
